### PR TITLE
QMMHarmonyShimmer: Improved logging for invalid assemblies

### LINKED ISSUE #176: Harmony shimmer failing in some cases
**Describe the bug**
Some users are reporting an error stopping some mods from being loaded. Issue seems to be coming from our Harmony shim, log output as follows. 

```
[Debug] [Info   :QMMHarmonyShimmer] Shimming QMods...
[Debug] [Error  :QMMHarmonyShimmer] Failed to shim 0Harmony.dll
[Debug] [Error  :QMMHarmonyShimmer] System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
  at Mono.Cecil.PE.ImageReader.ReadImage () [0x00013] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.PE.ImageReader.ReadImage (Mono.Disposable`1[T] stream, System.String file_name) [0x00007] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00006] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream, Mono.Cecil.ReaderParameters parameters) [0x00018] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream) [0x00007] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.IO.Stream stream) [0x00000] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at QModManager.QMMHarmonyShimmer.QMMHarmonyShimmer.ShimQMods () [0x00179] in <2c45d767c91a491984d51c42609253d7>:0
[Debug] [Error  :QMMHarmonyShimmer] Failed to shim YamlDotNet.dll
[Debug] [Error  :QMMHarmonyShimmer] System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
  at System.IO.BinaryReader.ReadBytes (System.Int32 count) [0x00013] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Mono.Cecil.PE.ImageReader.ReadDebugHeader () [0x000f7] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.PE.ImageReader.ReadImage () [0x000a8] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.PE.ImageReader.ReadImage (Mono.Disposable`1[T] stream, System.String file_name) [0x00007] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00006] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream, Mono.Cecil.ReaderParameters parameters) [0x00018] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream) [0x00007] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.IO.Stream stream) [0x00000] in <6034b380a22b41a596c9dc29d282c0a9>:0 
  at QModManager.QMMHarmonyShimmer.QMMHarmonyShimmer.ShimQMods () [0x00179] in <2c45d767c91a491984d51c42609253d7>:0
```

This seems to be happening when the assembly being looked at is not in the correct format (probably unmanaged), and is often also happening when some mod authors are distributing their own version of 0Harmony.dll with their mod (oof - we should probably make it clear in the docs that this is a VERY BAD IDEA).

Posting this here as a reminder for myself to look into this ASAP.

### PR DESCRIPTION
**Pull request by tobeyStraitjacket**
- Spefically catching the `BadImageFormatException` thrown when we attempt to shim an assembly that is not a valid format (ie. unmanaged) and improved logging for this.

- Also added log warnings when any version of `0Harmony.dll` is detected in a QMod subfolder to allow users, modders and support-staff alike to know that this will very likely cause issues and the mod should be updated or removed.

Closes #176

### CODE REVIEW

File: QMMHarmonyShimmer/QMMHarmonyShimmer.cs [hunk 1]
```diff
@@ -218,10 +218,21 @@ private static void ShimQMods()
                             }
                         }
                     }
+                    catch (BadImageFormatException)
+                    {
+                        if (Path.GetFileName(filePath).Contains("0Harmony"))
+                            Logger.LogWarning($"QMod in folder {Path.GetDirectoryName(subfolderPath)} is shipping its own version of Harmony! " +
+                                $"This is NOT RECOMMENDED and can lead to serious compatibility issues with other mods! " +
+                                $"If you are a mod author, please do not ship Harmony with your mods, and instead rely on QModManager to load it for you.");
```
Comment (PrimeSonic) [inline QMMHarmonyShimmer/QMMHarmonyShimmer.cs:226]: Add a link to the QModManager wiki in this log where we detail where the new Harmony DLL is located.

Comment (tobeyStraitjacket) [reply QMMHarmonyShimmer/QMMHarmonyShimmer.cs]: 4734fe3
